name: CI_IBM

on: [push]

jobs:
  build:
    runs-on: maven:3.8.6-openjdk-18
    steps:
    - name: Gerando build
      run: mvn package -Dmaven.test.skip
    - name: Rodando teste unidade
      run: mvn test